services:
  - type: web
    name: cognisense-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: COGNISENSE_HOST_PIN
        sync: false
